# -*- mode: ruby -*-

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Box image name
  config.vm.box = "ubuntu/trusty64"

  # Bootstrap script
  config.vm.provision :shell, path: "bootstrap.sh"

  # Sync directories
  config.vm.synced_folder "../", "/home/vagrant/units3/"

  # Activate private network with DHCP
  # config.vm.network "private_network", type: "dhcp"

  # Forward host port 8080 to guest port 5000
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  config.vm.provider "virtualbox" do |vb|
    # Change memory to 1024MB
    vb.customize ["modifyvm", :id, "--memory", 1024]
    # Change cpus to 2
    vb.customize ["modifyvm", :id, "--cpus", 2]
  end
end
